services:
    ansible:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        volumes:
            - ${HOST_AUTHORIZED_SSH_PRIVATE_KEY}:/root/.ssh/id_rsa
            - ${HOST_ANSIBLE_INVENTORY_FILE}:/workspace/ansible/inventory/hosts
            - ./:/workspace
        network_mode: host
