- name: Docker Volumes
  ansible.builtin.import_playbook: docker_volumes.yml
  vars:
    hosts_override: all

- name: Docker Networks
  ansible.builtin.import_playbook: docker_networks.yml
  vars:
    hosts_override: all

- name: Docker Containers
  ansible.builtin.import_playbook: docker_containers.yml
  vars:
    hosts_override: all
